server:
  port: 2222
spring:
  application:
    name: order-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1111/eureka/
  instance:
    hostname: order-service
    prefer-ip-address: true